# fly.toml app configuration file generated for ruby-birthday-bonanza-autumn-sound-7009 on 2024-05-13T12:22:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ruby-birthday-bonanza'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DATABASE_URL = "sqlite:///mnt/volume/data.sqlite3"

[mounts]
  source = "sqlite3_volume"
  destination = "/mnt/volume"
